export const sampleData = [
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": "2026-06-25",
    "Actual Date": null,
    "Part Name": "14MW Yaw Ring",
    "Model": "Single Ring",
    "Qty Target": 6,
    "Stock": 2,
    "Completed": 1,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "6/27/2026 đo ring thứ 2",
    "Status": "Open",
    "Balance": 5,
    "Progress %": 0.166667
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-08",
    "Plan Date": "2026-06-24",
    "Actual Date": null,
    "Part Name": "15MW Yaw Ring",
    "Model": "Single Ring",
    "Qty Target": 8,
    "Stock": 4,
    "Completed": 2,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "6/23/2026 dự kiến giao ring thứ 4",
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.25
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "SG129 MY20 Yaw Ring",
    "Model": "Single Ring",
    "Qty Target": 15,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "SX chưa có kế hoạch giao",
    "Status": "Open",
    "Balance": 15,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 2",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 1",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 3,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 3,
    "Progress %": 0.5
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 1,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 5,
    "Progress %": 0.166667
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner Assemply",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer Radial + Gap",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Assemply",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 2",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 1",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 1,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 11,
    "Progress %": 0.083333
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 2,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 10,
    "Progress %": 0.166667
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner Assemply",
    "Qty Target": 12,
    "Stock": 7,
    "Completed": 7,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 5,
    "Progress %": 0.583333
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 12,
    "Stock": 6,
    "Completed": 8,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 4,
    "Progress %": 0.666667
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Assemply",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 2",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 1",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner Assemply",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-17",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Assemply",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 2",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner 1",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Inner Assemply",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Outer Radial + Gap",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-24",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Blade Bearing",
    "Model": "Assemply",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0.0
  },
  {
    "Category": "1/30",
    "Ref No": "W26",
    "Due Date": null,
    "Plan Date": "2026-06-25",
    "Actual Date": null,
    "Part Name": "2.8-127 Pitch O-Bearing",
    "Model": "Outer",
    "Qty Target": 9,
    "Stock": 9,
    "Completed": 4,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 5,
    "Progress %": 0.444444
  },
  {
    "Category": "1/30",
    "Ref No": "W26",
    "Due Date": null,
    "Plan Date": "2026-06-24",
    "Actual Date": null,
    "Part Name": "Sierra N1 Pitch Bearing",
    "Model": "Inner",
    "Qty Target": 4,
    "Stock": 4,
    "Completed": 3,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.75
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2605-02",
    "Due Date": null,
    "Plan Date": "2026-06-25",
    "Actual Date": null,
    "Part Name": "Cypress Yaw Bearing",
    "Model": "Inner",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 0,
    "Ring SN": "GEEYOA4X000052601E20",
    "CMM Features": "Data Gear (Datum B & GearTip)",
    "Comment": "ITR sai tên hàng",
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.0
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-6",
    "Due Date": null,
    "Plan Date": "2026-06-26",
    "Actual Date": null,
    "Part Name": "2.8-127 Pitch O-Bearing",
    "Model": "Inner 1",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 0,
    "Ring SN": "GEEPIB2X002732612G25",
    "CMM Features": "Theo Sketch ITR",
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.0
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-12",
    "Due Date": null,
    "Plan Date": "2026-06-24",
    "Actual Date": null,
    "Part Name": "2.x Yaw Bearing",
    "Model": "Outer",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 0,
    "Ring SN": "GEEYOA2X000032613B26",
    "CMM Features": "Profile and Lead",
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.0
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-14",
    "Due Date": null,
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "1.x-97 Pitch Bearing",
    "Model": "Inner",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 0,
    "Ring SN": "GEEPIA1X009712616E05",
    "CMM Features": "Raceway dimensions (After rework)",
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.0
  },
];