export const sampleData = [
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-03",
    "Plan Date": "2026-06-25",
    "Actual Date": null,
    "Part Name": "SG14 Yaw Ring",
    "Qty Target": 6,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "6/24/2026 dự kiến giao ring thứ 1\nRing thứ 2 và 3 đang OP80\nRing 4 , 5 ,6 chưa có thời gian dự kiến.",
    "Status": "Open",
    "Balance": 6,
    "Progress %": 0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-08",
    "Plan Date": "2026-06-23",
    "Actual Date": null,
    "Part Name": "VESTAS 15MW Yaw Ring",
    "Qty Target": 4,
    "Stock": 3,
    "Completed": 2,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "6/23/2026 dự kiến giao ring thứ 4",
    "Status": "Open",
    "Balance": 2,
    "Progress %": 0.5
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "SG129 MY20 Yaw Ring",
    "Qty Target": 15,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "SX chưa có kế hoạch giao",
    "Status": "Open",
    "Balance": 15,
    "Progress %": 0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Inner Lower",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Inner Upper",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Outer",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Inner Assemply",
    "Qty Target": 12,
    "Stock": 7,
    "Completed": 7,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 5,
    "Progress %": 0.5833333333333334
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Outer Radial + Gap",
    "Qty Target": 12,
    "Stock": 5,
    "Completed": 5,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 7,
    "Progress %": 0.4166666666666667
  },
  {
    "Category": "Shipment",
    "Ref No": null,
    "Due Date": "2026-07-10",
    "Plan Date": null,
    "Actual Date": null,
    "Part Name": "V172 Assemply",
    "Qty Target": 12,
    "Stock": 0,
    "Completed": 0,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 12,
    "Progress %": 0
  },
  {
    "Category": "1/30",
    "Ref No": null,
    "Due Date": "W25",
    "Plan Date": "2026-06-20",
    "Actual Date": "2026-06-20",
    "Part Name": "2.X-127 O-Bearing Pitch Outer",
    "Qty Target": 9,
    "Stock": 9,
    "Completed": 9,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Completed",
    "Balance": 0,
    "Progress %": 1
  },
  {
    "Category": "1/30",
    "Ref No": null,
    "Due Date": "W25",
    "Plan Date": "2026-06-21",
    "Actual Date": null,
    "Part Name": "1.6 Hybrid Glass Pitch Bearing-Inner",
    "Qty Target": 2,
    "Stock": 2,
    "Completed": 1,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.5
  },
  {
    "Category": "1/30",
    "Ref No": null,
    "Due Date": "W25",
    "Plan Date": null,
    "Actual Date": "2026-06-19",
    "Part Name": "2.X Yaw Bearing - Inner",
    "Qty Target": 2,
    "Stock": 2,
    "Completed": 2,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": null,
    "Status": "Completed",
    "Balance": 0,
    "Progress %": 1
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2605-02",
    "Due Date": null,
    "Plan Date": "2026-06-25",
    "Actual Date": null,
    "Part Name": "WT19 Cypress Yaw Bearing - Inner",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": null,
    "Ring SN": "GEEYOA4X000052601E20",
    "CMM Features": "Data Gear (Datum B & GearTip)",
    "Comment": "ITR sai tên hàng",
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0
  },
  {
    "Category": "ITR",
    "Ref No": "CS-RC-553423-0-01",
    "Due Date": null,
    "Plan Date": "2026-06-21",
    "Actual Date": "2026-06-21",
    "Part Name": "Cage 55X55L",
    "Qty Target": 2,
    "Stock": 2,
    "Completed": 2,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "Đã có CAD",
    "Status": "Completed",
    "Balance": 0,
    "Progress %": 1
  },
  {
    "Category": "ITR",
    "Ref No": "CS-RC-203316-0-00",
    "Due Date": null,
    "Plan Date": "2026-06-21",
    "Actual Date": null,
    "Part Name": "Cage 20X20L",
    "Qty Target": 2,
    "Stock": 2,
    "Completed": 1,
    "Ring SN": null,
    "CMM Features": null,
    "Comment": "Đã có CAD",
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0.5
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-6",
    "Due Date": null,
    "Plan Date": "2026-06-26",
    "Actual Date": null,
    "Part Name": "2.X-127 O-Bearing Pitch Inner Upper",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": null,
    "Ring SN": "GEEPIB2X002732612G25",
    "CMM Features": "Theo Sketch ITR",
    "Comment": null,
    "Status": "Open",
    "Balance": 1,
    "Progress %": 0
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-7",
    "Due Date": null,
    "Plan Date": "2026-06-20",
    "Actual Date": null,
    "Part Name": "2.X-127 O-Bearing Pitch Outer",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 1,
    "Ring SN": "GEEPOA280000B2623B12",
    "CMM Features": "Theo Sketch ITR",
    "Comment": "Đã gửi report GW",
    "Status": "Completed",
    "Balance": 0,
    "Progress %": 1
  },
  {
    "Category": "ITR",
    "Ref No": "VN-CP-CP60.9-2606-7",
    "Due Date": null,
    "Plan Date": "2026-06-20",
    "Actual Date": null,
    "Part Name": "2.X-127 O-Bearing Pitch Outer",
    "Qty Target": 1,
    "Stock": 1,
    "Completed": 1,
    "Ring SN": "GEEPOA280000B2623B11",
    "CMM Features": "Theo Sketch ITR",
    "Comment": "Đã đo (lấy đo 1/30)",
    "Status": "Completed",
    "Balance": 0,
    "Progress %": 1
  }
];
